### ISSUE TITLE
Externalize application title

### ISSUE THREAD

**Issue by DaveJarvis** [css4j/echosvg#6]
Create a class similar to JCLF's `ApplicationInfo` that can import application information from an external source, such as a `properties` file.

**Comment by carlosame** [comment]
Depends on #5.

**Comment by carlosame** [comment]
Do you have an actual use case for having the application title (library title in this case) in a resource file? If so, perhaps I could figure out which approach to follow.

EchoSVG currently contains a couple of applications, and one of them (named "svgbrowser") does have its name in a properties file: `test-resources/io/sf/carte/echosvg/apps/svgbrowser/Main.properties`. But that's probably not what you want.

In order to proceed, I need to understand the use case.

**Comment by DaveJarvis** [comment]
> In order to proceed, I need to understand the use case.

I think it was mostly because Batik had me a little gun-shy. For example, I had _no idea_ that it was sending its name out over HTTP requests. If the name was a constant defined in a single location, and used consistently from the single point, I could find all occurrences in the code base and be fairly certain there were no "gotchas", like with Batik. It's not so much a use case as peace of mind.

**Comment by carlosame** [comment]
I am not aware of any other place where EchoSVG is putting its name, although some tests do that in their generated output (where they use the `SVGGeneratorContext.setComment(String)` method which can be used to customize generated SVG).

But AFAIK you do not use generated SVG so that does not affect you (and the default is `null` which means that no comment is put).

**Comment by DaveJarvis** [comment]
Closing, we don't need to fix this.
